### ISSUE TITLE
Brick doesn't build

### ISSUE THREAD

**Issue by tylerdq** [SamTay/conway#2]
I'm trying to compile from source with cabal on my installation of KISS Linux using these build commands:

```
cabal update
cabal build
cabal install life
```

I get the following error:

```
src/Brick/Main.hs:76:5: error:  
    Module ‘Graphics.Vty’ does not export ‘mkVty’  
   |  
76 |   , mkVty  
   |     ^^^^^  
Error: cabal: Failed to build brick-0.72 (which is required by exe:life from  
conway-0.1.0.0). See the build log above for details
```

This is strange because your games `tetris` and `snake` compile brick fine with similar commands. Is it possible to compile `conway` with cabal like these other games, or is stack really a hard requirement?

**Comment by samtay** [comment]
This is likely because this repo hasn't been updated in years. The stack option is best in this case as it will use the configured LTS with all of the very outdated pinned dependencies.

**Comment by tylerdq** [comment]
Ahh thanks so much, that helps to know!
